class MLGB:
        def __init__(self,**paras):
		pass
        def stripoffHtml(self,words):
		text = words.replace("<p>","")
		words = text.replace("</p>","")
		words = words.replace("<strong>","")
		words = words.replace("</strong>","")
		words = words.replace("<em>","")
		words = words.replace("</em>","")
		words = words.replace('<span style="text-decoration: underline;">',"")
		words = words.replace("</span>","")
		words = words.replace("<i>","")
		words = words.replace("</i>","")
		words = words.replace("<ul>","")
		words = words.replace("</ul>","")
		words = words.replace("<li>","")
		words = words.replace("</li>","")
		words = words.replace("<ol>","")
		words = words.replace("</ol>","")
		words = words.replace("<sub>","")
		words = words.replace("</sub>","")
		words = words.replace("<sup>","")
		words = words.replace("</sup>","")
		words = words.replace('<span style="text-decoration: line-through;">',"")
		words = words.replace("&nbsp;","")
		words = words.replace('<span class="cccc">',"")
		words = words.replace('<div class="msLong_contentsTextTitle">',"")
		words = words.replace("</div>","")
		words = words.replace('<a name="text_number1">',"")
		words = words.replace('</a>',"")
		words = words.replace('<div class="msLong_contentsItem">',"")
		words = words.replace('<a name="text_number5">',"")
		words = words.replace('<div class="msLong_contentsItemSeparator">',"")
		words = words.replace('<br />',"")
		#text = text.replace("&uacute;","&#250;")
		return(words)